from django.core.management.base import BaseCommand
from core.models import Course, Lesson

class Command(BaseCommand):
    help = 'Completes First Aid with Modules 5-12 at BBP-level depth'

    def handle(self, *args, **options):
        try:
            course = Course.objects.get(title='Standard First Aid')
            
            lessons = [
                {
                    'order': 5,
                    'title': 'Module 5: Musculoskeletal Injuries: Beyond R.I.C.E.',
                    'content': """
                        <p>Musculoskeletal injuries—including fractures, dislocations, sprains, and strains—are among the most common reasons for seeking first aid. In 2026, the traditional R.I.C.E. (Rest, Ice, Compression, Elevation) method has been largely superseded in professional sports medicine by the <strong>PEACE & LOVE</strong> protocol, though the fundamentals remain useful for immediate layperson care. A fracture (a break in the bone) can be "closed" or "open" (where the bone protrudes through the skin). Open fractures carry a massive risk of infection and require immediate sterile covering. Your primary goal is <strong>Immobilization</strong>. Moving a fractured limb can cause the sharp bone ends to sever nearby nerves or blood vessels, leading to permanent disability or life-threatening hemorrhage.</p>
                        <p>Splinting is the act of using a rigid object to prevent movement of the joints above and below the injury site. You should only splint if you must move the victim and it does not cause additional pain. The 2026 standard emphasizes the "Splint it as it lies" rule—never attempt to straighten or "reset" a deformed limb. Check for "CSM" (Circulation, Sensation, and Movement) before and after applying a splint. If the victim loses a pulse in the limb or feels numbness after you tie the splint, it is too tight and must be loosened immediately. For dislocations (where a bone is out of its socket), never attempt to pop the bone back in, as this can crush the surrounding soft tissue.</p>
                        <p>Soft tissue injuries like sprains (ligament tears) and strains (muscle/tendon tears) require management of the inflammatory response. While ice is still used for pain management, the 2026 focus is on <strong>Optimal Loading</strong> rather than total rest. Avoid "H.A.R.M." (Heat, Alcohol, Running, and Massage) in the first 72 hours, as these can increase swelling and delay tissue repair. If a victim has a suspected pelvic or femur fracture, these are considered medical emergencies due to the potential for massive internal blood loss; keep the victim completely still and treat for shock while awaiting EMS.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Immobilize fractures and check for circulation/sensation (CSM).</li><li>Never attempt to "reset" a dislocation or straighten a deformed limb.</li></ul></div>"""
                },
                {
                    'order': 6,
                    'title': 'Module 6: Head, Neck, and Spinal Injuries',
                    'content': """
                        <p>Injuries to the Central Nervous System (CNS) are high-stakes events where the rescuer’s primary duty is to "Do No Harm." Any significant blunt force trauma—such as a fall from a height, a high-speed motor vehicle accident, or a diving incident—must be treated as a suspected spinal injury. The 2026 standard for laypersons is <strong>Manual Stabilization</strong>. This means placing your hands on both sides of the victim’s head to keep them from moving. You should not use a cervical collar (C-collar) unless you are professionally trained; improper application can actually increase intracranial pressure or compromise the airway.</p>
                        <p>Traumatic Brain Injuries (TBI), commonly known as concussions, are evaluated using updated 2026 <strong>SCAT6 (Sport Concussion Assessment Tool)</strong> indicators. Look for "Red Flag" symptoms: repeated vomiting, seizure activity, one pupil larger than the other, or increasing confusion/combativeness. If a victim lost consciousness for any amount of time, they must be cleared by a physician before returning to activity. A dangerous myth is that you must keep a concussion victim awake; the current medical consensus is that sleep is acceptable once a professional has ruled out an intracranial bleed, but the victim should be monitored for changes in breathing patterns.</p>
                        <p>If a victim with a suspected spinal injury is vomiting or their airway is blocked by blood, you must perform a <strong>Log Roll</strong>. This requires at least two (ideally three) rescuers to move the victim as a single unit, ensuring the head, neck, and torso remain in perfect alignment. One rescuer must maintain control of the head and give the commands for the roll. If you are alone and must move a victim to save their life, use the "Clothes Drag" technique, pulling them in the direction of the long axis of the body to minimize spinal torque.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Keep the head and neck aligned; avoid unnecessary movement.</li><li>"Red Flags" for head injuries (vomiting, pupil changes) require immediate 911.</li></ul></div>"""
                },
                {
                    'order': 7,
                    'title': 'Module 7: Sudden Medical Emergencies: Stroke & Diabetes',
                    'content': """
                        <p>Sudden medical emergencies occur when an underlying chronic condition or an acute internal event disrupts the body’s homeostasis. <strong>Stroke</strong> (Cerebrovascular Accident) occurs when blood flow to the brain is interrupted by a clot or a burst vessel. In 2026, the <strong>F.A.S.T.</strong> mnemonic remains the gold standard: Face (is one side drooping?), Arm (does one arm drift downward when raised?), Speech (is it slurred or strange?), and Time (if any of these are present, call 911 immediately). Modern neurology emphasizes that "Time is Brain"; every minute a stroke goes untreated, the brain loses nearly 2 million neurons.</p>
                        <p>Diabetic emergencies are usually caused by <strong>Hypoglycemia</strong> (low blood sugar), which can cause a victim to appear confused, aggressive, or "drunk." If the victim is conscious and can swallow, provide 15 to 20 grams of fast-acting sugar (glucose tablets, juice, or regular soda). If you are unsure if their sugar is too high or too low, give sugar anyway; low blood sugar is an immediate threat to the brain, while a temporary increase in high blood sugar is less acutely dangerous in an emergency setting. If they are unconscious, do not put anything in their mouth; instead, call 911 and monitor their airway.</p>
                        <p><strong>Seizures</strong> are caused by abnormal electrical activity in the brain. The 2026 first aid priority is "Clear and Protect." Do not restrain the victim or attempt to put anything between their teeth; this is an outdated practice that causes broken teeth and jaw injuries. Instead, clear the area of hard or sharp objects and place something soft under their head. Most seizures last less than five minutes. Once the shaking stops, the victim will enter a "Post-Ictal State" where they are very drowsy and confused. Turn them onto their side (Recovery Position) and stay with them until they are fully alert.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Use F.A.S.T. for strokes; time is the most critical variable.</li><li>For seizures: Protect the head, do not restrain, and place in recovery position after.</li></ul></div>"""
                },
                {
                    'order': 8,
                    'title': 'Module 8: Environmental: Heat and Cold Physics',
                    'content': """
                        <p>Environmental emergencies are the result of the body’s thermoregulatory systems failing to cope with extreme temperatures. <strong>Heat Stroke</strong> is a true medical emergency where the body temperature rises above 104°F (40°C). Unlike heat exhaustion (where the victim sweats profusely), a victim in heat stroke may have stopped sweating entirely and will show signs of Central Nervous System dysfunction, such as confusion or fainting. The 2026 standard for heat stroke is <strong>"Cool First, Transport Second."</strong> This means using aggressive cooling methods like "Cold Water Immersion" (ice baths) if available, or wrapping the victim in wet sheets and using fans to induce evaporative cooling before the ambulance departs.</p>
                        <p>On the opposite end of the spectrum is <strong>Hypothermia</strong>, which occurs when the core body temperature drops below 95°F (35°C). In 2026, we emphasize "Passive Rewarming" for laypeople. Remove wet clothing, dry the skin, and wrap the victim in multiple layers of dry blankets or "space" blankets. Do not rub the victim's limbs to warm them, as this can force cold blood from the extremities back to the heart too quickly (afterdrop), leading to cardiac arrest. Provide warm, non-caffeinated, non-alcoholic liquids only if the victim is fully conscious and can safely swallow.</p>
                        <p><strong>Frostbite</strong> is the actual freezing of body tissue. Superficial frostbite (frostnip) involves the skin turning white or waxy. Deep frostbite involves the freezing of muscle and bone. The most critical 2026 rule: <strong>Do not attempt to rewarm a frostbitten area if there is any chance of it refreezing</strong>. Refreezing causes massive ice-crystal damage that almost always leads to amputation. If you must rewarm, use the "Controlled Bath" method—water between 100°F and 108°F (not hot). Never use dry heat like a hair dryer or fire, as the frostbitten skin is numb and will burn easily without the victim feeling it.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Heat Stroke requires immediate, aggressive cooling (Cool First, Transport Second).</li><li>Never rub frostbitten skin; only rewarm if refreezing is impossible.</li></ul></div>"""
                },
                {
                    'order': 9,
                    'title': 'Module 9: Toxicology: Opioids and Modern Poisoning',
                    'content': """
                        <p>Toxicology in 2026 is dominated by the threat of synthetic opioids and accidental household exposures. If you suspect a <strong>Poisoning by Ingestion</strong>, your first call should be to the National Poison Control Center (1-800-222-1222). Do not induce vomiting or administer Syrup of Ipecac unless specifically instructed to do so by a medical professional. Many corrosive chemicals (like drain cleaner) do more damage to the esophagus coming back up than they did going down. If the poison is a gas, such as <strong>Carbon Monoxide</strong>, move the victim to fresh air immediately. Remember that CO is odorless and colorless; if you feel dizzy or have a headache in a confined space, assume CO is present.</p>
                        <p>The 2026 response to <strong>Opioid Overdose</strong> is a critical life-saving skill. Synthetic opioids like Fentanyl are so potent they can cause "Chest Wall Rigidity" (Wooden Chest Syndrome), making CPR difficult. If a victim is unresponsive and breathing slowly (or not at all), administer <strong>Naloxone (Narcan)</strong> nasal spray immediately. It is non-addictive and harmless if the victim is not actually overdosing. Under modern Good Samaritan laws, laypeople are protected when carrying and using Narcan. Note that because of the potency of modern opioids, a second or third dose may be required every 2-3 minutes until the victim resumes normal breathing.</p>
                        <p>For <strong>Absorbed Poisons</strong> (chemicals on the skin), the rule is "The Solution to Pollution is Dilution." Flush the affected area with water for at least 20 minutes. If the poison is in the eyes, flush from the nose-side outward to prevent washing the chemical into the unaffected eye. For <strong>Injected Poisons</strong> (drug needles or stings), monitor for systemic reactions like anaphylaxis. Always try to identify the substance or bring the container to the hospital, but never put yourself at risk by handling leaking containers or dangerous needles directly.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Call Poison Control before inducing vomiting.</li><li>Administer Naloxone immediately for suspected opioid overdose; it is safe and legal.</li></ul></div>"""
                },
                {
                    'order': 10,
                    'title': 'Module 10: Anaphylaxis and Allergic Reactions',
                    'content': """
                        <p>Anaphylaxis is a severe, systemic allergic reaction that can lead to death in minutes by closing the airway and causing a catastrophic drop in blood pressure (anaphylactic shock). In 2026, we emphasize early recognition of the <strong>"Two-System" rule</strong>: if a victim has symptoms in two or more body systems (e.g., hives on the skin AND wheezing in the lungs), it is anaphylaxis. Common triggers include peanuts, shellfish, bee stings, and latex. The primary medication for this emergency is <strong>Epinephrine</strong>, which reverses the reaction by opening the airways and constricting blood vessels.</p>
                        <p>If the victim has an <strong>Epinephrine Auto-Injector (Epi-Pen)</strong>, assist them in using it immediately. Remove the safety cap, place the orange tip against the "mid-outer thigh" (it can go through clothing), and push firmly until you hear a click. Hold it in place for 3 seconds to ensure the full dose is delivered. After administration, massage the area for 10 seconds to increase absorption. Even if the victim feels better, you <strong>must call 911</strong>. Approximately 20% of victims experience a "Biphase Reaction," where the symptoms return hours later after the epinephrine wears off.</p>
                        <p>If the victim does not improve within 5 to 10 minutes and EMS has not arrived, a <strong>second dose</strong> of epinephrine should be administered if available. While waiting, keep the victim lying flat with their legs elevated to combat low blood pressure, unless they are having significant trouble breathing, in which case they should sit up. Avoid giving oral antihistamines (like Benadryl) as a primary treatment for anaphylaxis; they work too slowly to save a life and can mask symptoms that indicate the reaction is worsening.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Epinephrine is the only effective treatment for anaphylaxis.</li><li>Inject into the mid-outer thigh and always call 911 for follow-up care.</li></ul></div>"""
                },
                {
                    'order': 11,
                    'title': 'Module 11: Bites, Stings, and Zoonotic Risks',
                    'content': """
                        <p>Bites and stings range from minor annoyances to life-threatening venomous exposures. In 2026, <strong>Tick-Borne Illnesses</strong> (Lyme disease, Alpha-gal syndrome) are a growing concern. If you find a tick, use fine-tipped tweezers to grasp it as close to the skin as possible and pull upward with steady, even pressure. Do not use heat, petroleum jelly, or "twisting" motions, as these can cause the tick to regurgitate its stomach contents into the wound, increasing the risk of infection. Clean the area with alcohol and save the tick in a jar for testing if symptoms (like a bullseye rash) appear later.</p>
                        <p><strong>Venomous Snakebites</strong> in North America (Rattlesnakes, Copperheads) require a "Keep it Simple" approach. The 2026 guidelines explicitly forbid outdated "Wilderness" tactics: <strong>Do not use a tourniquet, do not use suction, and do not use ice</strong>. Suction kits are ineffective at removing venom and often damage tissue. Instead, keep the victim calm and still (to slow venom travel), remove any rings or watches (due to swelling), and keep the bitten limb at or slightly below the level of the heart. Identify the snake if possible, but do not attempt to capture it; a photo is sufficient for the hospital to determine the correct antivenom.</p>
                        <p><strong>Animal and Human Bites</strong> carry a high risk of infection and, in the case of wild animals, <strong>Rabies</strong>. Rabies is 100% fatal once symptoms appear, so any bite from a bat, raccoon, or unknown dog must be treated as a potential exposure. Immediately wash the wound with soap and water for at least 15 minutes. This mechanical washing is extremely effective at reducing the viral load. Seek medical attention immediately for the "Rabies Post-Exposure Prophylaxis" (PEP) series, which is highly effective if started before symptoms begin.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Remove ticks with tweezers by pulling straight up; don't use heat.</li><li>For snakebites: No ice, no suction, no tourniquets—just stay still and call 911.</li></ul></div>"""
                },
                {
                    'order': 12,
                    'title': 'Module 12: Psychological First Aid and Rescuer Care',
                    'content': """
                        <p>First aid is not just about physical wounds; it is about the person behind the injury. <strong>Psychological First Aid (PFA)</strong> is a modular approach to help people in the immediate aftermath of a crisis. Use the "Look, Listen, Link" framework. <strong>Look</strong> for people with urgent basic needs or those showing signs of severe distress. <strong>Listen</strong> to their concerns without forcing them to talk, providing a calm and non-judgmental presence. <strong>Link</strong> them to their loved ones and professional resources. Avoid "toxic positivity" (e.g., "It could be worse"); instead, validate their feelings and provide factual information about what is happening.</p>
                        <p>Rescuers must also practice <strong>Self-Care and Stress Management</strong>. Providing first aid in a high-stress situation—especially involving a child or a severe trauma—can lead to "Compassion Fatigue" or acute stress reactions. Symptoms can include intrusive thoughts, irritability, or feeling "numb." In 2026, the industry standard is to hold a "Defusing" session within 24 hours of an event—a short, informal talk to check in on the team’s mental state. This is distinct from a "Debriefing," which is a more formal clinical process that happens days later.</p>
                        <p>Finally, remember the <strong>Rescuer\'s Mindset</strong>. You are a bridge between the accident and the hospital. You cannot control the final outcome of a victim’s injury, but you can control the quality of the care and the compassion you provide. By maintaining your certification and your own mental health, you ensure that you remain a reliable and effective resource for your community. First aid is a lifelong skill; continue to practice and stay updated on the latest 2026 guidelines to provide the best possible chance for those in need.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Use "Look, Listen, Link" for Psychological First Aid.</li><li>Rescuers must prioritize their own mental health to remain effective.</li></ul></div>"""
                }
            ]

            for l_data in lessons:
                Lesson.objects.create(course=course, **l_data)
            
            self.stdout.write(self.style.SUCCESS(f'SUCCESS: First Aid Ultimate Upgrade Complete.'))
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'Error: {e}'))
