from django.core.management.base import BaseCommand
from core.models import Course, Lesson

class Command(BaseCommand):
    help = 'Upgrades CPR/AED to 12 Deep-Dive World-Class Modules'

    def handle(self, *args, **options):
        try:
            course = Course.objects.get(title='Standard CPR / AED')
            # Clear all existing and overwrite with the 12-module set
            course.lessons.all().delete()

            lessons = [
                {
                    'order': 1,
                    'title': 'The 2026 Chain of Survival: A Systems Approach',
                    'content': """
                        <p>The Chain of Survival is the internationally recognized clinical framework for maximizing the probability of survival following a Sudden Cardiac Arrest (SCA). In 2026, the standard has transitioned into a <strong>6-link system</strong> that emphasizes a continuum of care starting from the second a victim collapses. The first three links—Early Recognition, High-Quality CPR, and Rapid Defibrillation—are the exclusive domain of the lay rescuer. Research indicates that for every minute that passes without these interventions, the probability of successful resuscitation drops by approximately 10%. By the time professional EMS arrives (typically 8-12 minutes in urban settings), the physiological window for survival has often closed unless a bystander has initiated the chain.</p>
                        <p>The 2026 guidelines introduce the <strong>Recovery Link</strong> as the sixth and final component of the chain. This link acknowledges that survival is not merely the return of spontaneous circulation (ROSC), but a long-term process involving neurological rehabilitation and psychological support. Sudden Cardiac Arrest is a massive physical and emotional trauma; the Recovery Link mandates that discharge planning include assessments for anxiety, depression, and post-cardiac arrest syndrome. It also emphasizes the importance of "Rescuer Support," providing mental health resources for the laypeople who performed the life-saving measures, as the stress of the event can have lasting impacts.</p>
                        <p>As a certified rescuer, you are the most critical variable in this system. Clinical data proves that "Hands-Only" CPR initiated by a bystander can double or triple a victim's chance of survival. This module establishes the mindset that you are not merely a witness, but a vital medical link. Your goal is to maintain perfusion—the flow of oxygenated blood—to the brain and heart until the heart can be "restarted" by an AED or advanced medical intervention. This course will provide the technical depth required to perform these links with the precision of a professional responder.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>The 2026 Chain has 6 links, culminating in long-term Recovery and Rescuer Support.</li><li>Bystander action is the most critical factor in out-of-hospital survival.</li></ul></div>"""
                },
                {
                    'order': 2,
                    'title': 'Legal Rights, Ethics, and Scene Safety',
                    'content': """
                        <p>Before any physical intervention occurs, a rescuer must navigate the legal and environmental landscape of an emergency. The <strong>Good Samaritan Laws</strong> exist in all 50 states to protect lay rescuers who provide assistance in good faith, without gross negligence, and without expectation of compensation. In 2026, these laws have been strengthened to specifically include protection for the administration of Naloxone and the use of public-access AEDs. However, the legal concept of <strong>Consent</strong> remains paramount. For a conscious adult, you must ask for permission ("I am certified in CPR, can I help you?"). For an unconscious victim, consent is "Implied," meaning the law assumes a reasonable person would want life-saving care.</p>
                        <p>Scene assessment is a critical, continuous process that ensures the rescuer does not become a second victim. In 2026, safety protocols have expanded to include <strong>Environmental Hazards</strong> such as electrical lines, toxic fumes, and active traffic. You must evaluate the "Mechanism of Injury"—understanding what caused the event—to ensure you are not entering a "Kill Zone" (such as a room with a carbon monoxide leak). If the scene is unsafe, you must stay back and wait for professional specialized units. Rescuer safety is always the priority; a dead or injured rescuer cannot save anyone.</p>
                        <p>Ethical considerations also involve the recognition of "Do Not Resuscitate" (DNR) orders or Physician Orders for Life-Sustaining Treatment (POLST). While these documents are rarely available in a sudden street collapse, in a home or facility setting, they must be honored if legally presented. However, the 2026 guideline for lay rescuers is "When in doubt, start CPR." It is ethically and legally better to initiate care and have it stopped later by a physician than to withhold potentially life-saving treatment due to uncertainty.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Good Samaritan laws protect rescuers acting in good faith without negligence.</li><li>Scene safety is the absolute first priority; implied consent applies to unconscious victims.</li></ul></div>"""
                },
                {
                    'order': 3,
                    'title': 'The Biomechanics of High-Quality Compressions',
                    'content': """
                        <p>Chest compressions are the mechanical substitute for a beating heart. To be effective, they must create enough intrathoracic pressure to force blood out of the heart and into the arterial system. In 2026, "High-Quality CPR" is defined by four strict clinical metrics: Depth, Rate, Recoil, and Minimal Interruptions. For an adult, you must compress the chest to a <strong>depth of 2 to 2.4 inches (5 to 6 cm)</strong>. Pushing shallower than 2 inches is a "non-perfusing" event, meaning the blood never reaches the brain. Conversely, pushing deeper than 2.4 inches significantly increases the risk of catastrophic internal injuries, such as liver lacerations or rib fractures that can puncture the lungs.</p>
                        
                        <p>The compression rate is the "metronome" of survival. The current standard is <strong>100 to 120 compressions per minute</strong>. This specific window is based on the physics of the human heart; it allows the heart enough time to refilled with blood (diastolic filling) while maintaining high enough mean arterial pressure to keep brain cells alive. If you exceed 120 BPM, the heart does not have time to refill, and you are effectively "pumping an empty chamber." If you fall below 100 BPM, the pressure in the system drops too low to fight gravity and reach the cerebral cortex.</p>
                        <p>The most commonly overlooked component of CPR is <strong>Full Chest Recoil</strong>. Between every compression, you must allow the chest to return completely to its natural position without "leaning" on the victim. Leaning—maintaining even slight pressure on the chest during the upstroke—prevents the heart from expanding and refilling with blood. Finally, interruptions must be minimized; every time you stop compressions (to check a pulse or move the victim), the blood pressure in the system immediately crashes to zero. It takes nearly 10-15 continuous compressions to build that pressure back up to a perfusing level. Therefore, you should never stop compressions for more than 10 seconds.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Maintain a depth of 2.0 to 2.4 inches and a rate of 100-120 BPM.</li><li>Ensure full chest recoil to allow the heart to refill with blood between strokes.</li></ul></div>"""
                },
                {
                    'order': 4,
                    'title': 'Advanced Airway Management and Ventilation',
                    'content': """
                        <p>While compressions move the blood, rescue breaths ensure that the blood being moved is carrying oxygen. In the first few minutes of a sudden collapse, the victim\'s blood contains a residual supply of oxygen. However, as the arrest progresses, or in cases of drowning and drug overdose, that oxygen is depleted, leading to cellular death. The 2026 standard for a single rescuer remains a <strong>ratio of 30 compressions to 2 rescue breaths</strong>. To deliver these breaths effectively, you must first open the airway using the <strong>Head-Tilt/Chin-Lift maneuver</strong>. This action lifts the tongue away from the posterior pharynx, which is the most common cause of airway obstruction in an unresponsive victim.</p>
                        <p>When delivering breaths, you are acting as the victim\'s lungs. Each breath should be delivered over <strong>one second</strong> with just enough volume to see the chest visibly rise. You must avoid "hyperventilation"—blowing too hard or too fast. Excessive air can enter the esophagus instead of the trachea, causing gastric inflation. This leads to vomiting and the potential for aspiration, where stomach contents enter the lungs, causing severe infection or blocking the airway entirely. Furthermore, excessive pressure in the chest can actually decrease the amount of blood that can return to the heart, making your compressions less effective.</p>
                        <p>In 2026, the use of a <strong>barrier device or pocket mask</strong> is mandatory for rescue breaths to protect the rescuer from infectious diseases (referencing Bloodborne Pathogen standards). If you do not have a barrier device, or if you are not trained in rescue breathing, you should provide <strong>Hands-Only CPR</strong> (continuous compressions). Hands-Only CPR is the preferred method for untrained bystanders and is highly effective for the first few minutes of a cardiac event. However, for infants, children, and victims of respiratory-based arrest (drowning/choking), rescue breaths are considered mandatory as their primary issue is oxygen depletion rather than a cardiac rhythm failure.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>The 30:2 ratio is the standard for adult, child, and infant CPR for single rescuers.</li><li>Provide breaths over 1 second, ensuring chest rise while avoiding gastric inflation.</li></ul></div>"""
                },
                {
                    'order': 5,
                    'title': 'Defibrillation: The Physics of the AED',
                    'content': """
                        <p>An Automated External Defibrillator (AED) is a high-precision medical device that analyzes the heart\'s electrical activity and determines if a shock is necessary. It is a common misconception that an AED "restarts" a dead heart. In reality, the AED is used to <strong>stop</strong> a heart that is in a lethal, chaotic rhythm, such as Ventricular Fibrillation (V-Fib). In V-Fib, the heart\'s electrical signals are firing randomly, causing the muscle to quiver rather than pump. The AED delivers a controlled burst of electricity that momentarily stops all electrical activity, allowing the heart\'s natural pacemaker (the SA Node) to re-establish a normal, organized rhythm.</p>
                        
                        <p>The 2026 generation of AEDs is designed for rapid deployment. The most critical step is to <strong>Turn the AED ON immediately</strong> upon its arrival. Once powered on, the device will provide verbal and visual prompts. You must apply the electrode pads to the victim\'s bare chest. The standard placement is "Anterolateral": one pad on the upper right chest (below the collarbone) and the other on the lower left ribs (below the armpit). For victims with hairy chests, you may need to use the "press and pull" method with a set of pads or a razor to ensure a clear electrical connection. If the victim has a visible medication patch, remove it with a gloved hand and wipe the area clean before applying the pad.</p>
                        <p>Safety during defibrillation is a non-negotiable legal and safety requirement. When the AED begins its analysis phase, you must loudly shout <strong>"Clear!"</strong> and ensure no one is touching the victim. Touching the patient during analysis can cause the AED to misinterpret your own heart rate or movement as the victim\'s rhythm. If a shock is advised, you must perform a final visual sweep from head to toe to ensure no one is in contact with the patient or any conductive surfaces (like a metal floor) before pressing the shock button. Immediately after the shock is delivered, you must resume chest compressions—do not wait for the AED to tell you to start. The heart is very weak after a shock and needs the mechanical support of CPR to maintain perfusion.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>The AED stops chaotic rhythms to allow a normal rhythm to return.</li><li>Rescuers must be "Clear" of the victim during analysis and shock delivery.</li></ul></div>"""
                },
                {
                    'order': 6,
                    'title': 'Pediatric Variations: Infants and Children',
                    'content': """
                        <p>Performing CPR on a child or infant requires significant adjustments in technique to account for their smaller physiology and different primary causes of cardiac arrest. Unlike adults, whose arrest is usually cardiac in nature, pediatric cardiac arrest is most often the result of respiratory failure or airway obstruction. Because of this, <strong>Oxygenation is critical</strong>. The 2026 guidelines emphasize that while "Hands-Only" CPR is acceptable for adults, it is insufficient for children and infants; rescue breaths must be integrated early and consistently to ensure survival.</p>
                        
                        <p>For a <strong>Child (Age 1 to Puberty)</strong>, the compression depth is approximately 2 inches (5 cm). You may use one or two hands depending on the size of the child, but the goal remains the same: compressing the chest at least one-third its total depth. For an <strong>Infant (Under Age 1)</strong>, the technique shifts to using two fingers (or the two-thumb encircling method) in the center of the chest, just below the nipple line. The depth for an infant is strictly 1.5 inches (4 cm). In both cases, the rate remains 100-120 compressions per minute, matching the adult tempo to maintain consistent blood pressure.</p>
                        <p>The 2026 standard for pediatric ventilation is highly specific. If you are the <strong>lone rescuer</strong>, you must maintain the 30:2 ratio (30 compressions to 2 breaths). However, if two trained rescuers are present, the ratio shifts to <strong>15:2</strong>. This increased frequency of breaths is designed to combat the rapid onset of hypoxia in pediatric patients. When delivering breaths to an infant, you should cover both the nose and mouth with your mask or mouth to create an effective seal. Each breath should be a gentle puff, just enough to see the chest rise, as their lung capacity is significantly smaller than an adult\'s.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Lone Rescuer ratio is 30:2; Two-Rescuer ratio is 15:2 for children/infants.</li><li>Infant depth is 1.5 inches; Child depth is 2 inches (or 1/3 chest depth).</li></ul></div>"""
                },
                {
                    'order': 7,
                    'title': 'Choking Protocols: Foreign Body Obstructions',
                    'content': """
                        <p>Choking is a common and terrifying emergency where time is the absolute enemy. The 2026 protocol distinguishes between a <strong>Mild Obstruction</strong> (where the victim can still cough, speak, or wheeze) and a <strong>Severe Obstruction</strong> (where the victim cannot breathe, cough, or speak, and may be clutching their throat). For a mild obstruction, your primary duty is to encourage the victim to keep coughing. Do not interfere with their natural efforts to clear the object, as a forceful cough is more effective than any manual maneuver.</p>
                        
                        <p>For a conscious adult or child with a severe obstruction, you must perform <strong>Abdominal Thrusts (the Heimlich Maneuver)</strong>. Stand behind the victim, wrap your arms around their waist, and make a fist. Place the thumb-side of your fist just above the navel (belly button) but well below the breastbone. Grasp your fist with your other hand and perform quick, upward, and inward thrusts. These thrusts simulate a cough by forcing air out of the lungs to dislodge the object. For pregnant or obese victims where you cannot wrap your arms around the waist, perform <strong>Chest Thrusts</strong> instead, placing your hands on the center of the breastbone.</p>
                        <p>If the victim becomes <strong>unconscious</strong>, you must immediately lower them to the floor and begin CPR, starting with chest compressions. The 2026 update emphasizes that you should not perform a "blind finger sweep" to find the object, as this often pushes the obstruction deeper into the throat. Instead, every time you open the airway to give breaths, look inside the mouth. If you see the object and it is easily accessible, remove it. If not, continue compressions. The mechanical action of chest compressions often creates enough upward pressure to move the object into the mouth where it can be safely cleared.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Perform Abdominal Thrusts above the navel for severe choking.</li><li>If a choking victim collapses, begin CPR starting with compressions.</li></ul></div>"""
                },
                {
                    'order': 8,
                    'title': 'The Lateral Recovery Position and Monitoring',
                    'content': """
                        <p>The Recovery Position is a vital but often skipped step in emergency care. It is used for victims who are <strong>unresponsive but breathing normally</strong> and do not have a suspected spinal injury. In this state, a victim’s muscles—including the tongue—relax significantly. If left lying flat on their back (supine), the tongue can fall backward and block the airway, or the victim may vomit and inhale the contents into their lungs (aspiration). The Recovery Position uses gravity to keep the airway clear and allows fluids to drain safely from the mouth.</p>
                        
                        <p>To place a victim in the <strong>Lateral Recovery Position</strong>, kneel beside them and extend the arm closest to you straight out at a right angle to the body. Take the far arm and place the back of their hand against their cheek closest to you. With your other hand, grasp the far leg just above the knee and pull it up so the foot is flat on the floor. Carefully pull the far knee toward you, rolling the victim onto their side. The hand under the cheek helps support the head, while the bent leg acts as a "kickstand" to prevent the victim from rolling onto their stomach.</p>
                        <p>Once in the position, you must continue to monitor the victim’s breathing closely. In 2026, rescuers are encouraged to use their smartphones to set a timer to check breathing every 2 minutes. If the victim\'s condition worsens or they stop breathing, you must roll them back onto their back and immediately begin CPR. The Recovery Position is a "holding pattern" that provides safety until professional medical help can take over the stabilization of the patient.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>The Recovery Position prevents airway obstruction by the tongue or vomit.</li><li>Regularly monitor breathing every 2 minutes while in the recovery position.</li></ul></div>"""
                },
                {
                    'order': 9,
                    'title': 'Opioid Overdose Response and Naloxone (Narcan)',
                    'content': """
                        <p>The opioid crisis has made <strong>Naloxone (Narcan)</strong> administration a standard component of modern CPR/AED training. Opioids (such as Fentanyl or Heroin) kill by suppressing the central nervous system’s drive to breathe. A victim of an opioid overdose will initially have a pulse but will be breathing very slowly or not at all (Respiratory Arrest). If left untreated, this quickly progresses to full Cardiac Arrest. In 2026, rescuers are trained to look for the "Opioid Triad": Unresponsiveness, Pinpoint Pupils, and Respiratory Depression (blue lips/fingernails).</p>
                        <p>If you suspect an overdose, <strong>Administer Naloxone immediately</strong>. Narcan is a nasal spray that temporarily "knocks" the opioids off the brain\'s receptors, allowing the victim to breathe again. To use it, insert the tip of the nozzle into a nostril and press the plunger. It is important to note that Naloxone has no effect on someone who is not experiencing an opioid overdose, so when in doubt, it is always safer to administer it. Under Good Samaritan laws, you are legally protected when providing this life-saving medication in good faith.</p>
                        <p>Crucially, <strong>Naloxone is not a substitute for CPR</strong>. If the victim has no pulse or is not breathing, you must continue high-quality CPR and use an AED while the medication takes effect. Naloxone typically takes 2 to 3 minutes to work. If the victim does not respond after the first dose, a second dose should be administered in the opposite nostril. Be prepared for the victim to wake up in a state of "Acute Withdrawal," which can include agitation, vomiting, or confusion. Stay with them until EMS arrives, as the Naloxone may wear off before the opioids leave their system, causing them to slip back into an overdose state.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Naloxone reverses respiratory depression caused by opioids.</li><li>Always perform CPR in tandem with Naloxone if the victim is not breathing.</li></ul></div>"""
                },
                {
                    'order': 10,
                    'title': 'High-Performance Team Dynamics',
                    'content': """
                        <p>While one-person CPR is life-saving, <strong>High-Performance Team CPR</strong> significantly increases the chance of survival by reducing "hands-off" time and rescuer fatigue. In a multi-rescuer situation, roles must be established immediately. One person performs compressions, the second manages the airway and rescue breaths, and the third operates the AED. This division of labor allows for continuous, high-quality care that mimics the efficiency of a professional hospital resuscitation team.</p>
                        <p>Rescuer fatigue is a major factor in CPR failure. Clinical studies show that compression quality (depth and rate) begins to degrade after just <strong>two minutes</strong> of continuous effort, even if the rescuer does not feel tired. To prevent this, rescuers should switch roles every two minutes, typically during the AED’s rhythm analysis phase. This "handoff" should take no more than five seconds. By rotating frequently, the team ensures that the victim is always receiving the most powerful, effective compressions possible.</p>
                        <p>Clear communication is the glue that holds a high-performance team together. Using <strong>Closed-Loop Communication</strong>—where the receiver repeats the command back to the sender—prevents errors in a high-stress environment. For example, if the AED operator says, "Everyone clear, I am delivering a shock," the compressor should respond, "Rescuer clear," before resuming compressions. This organized approach reduces chaos and ensures that every second of the intervention is dedicated to the victim’s survival.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Rotate compressors every 2 minutes to prevent fatigue and maintain quality.</li><li>Use closed-loop communication to ensure team safety and efficiency.</li></ul></div>"""
                },
                {
                    'order': 11,
                    'title': 'Special Circumstances and Environmental Hazards',
                    'content': """
                        <p>Real-world emergencies rarely happen in perfect conditions. Rescuers must be prepared for <strong>Special Circumstances</strong> that complicate CPR and AED use. One of the most common issues is a <strong>Drowning or Water-Related Event</strong>. If a victim is in water, you must move them to a dry surface before using an AED. While the victim’s chest does not need to be bone-dry, you must wipe the area where the pads will be placed to ensure proper adhesion and to prevent the electrical current from traveling across the water on the skin instead of through the heart.</p>
                        <p>Environmental obstacles like <strong>Metallic Surfaces or Pacemakers</strong> also require caution. If a victim is lying on a metal grate or floor, you can still use an AED, but ensure the pads do not touch the metal and that no one is in contact with the metal during the shock. If the victim has an implanted pacemaker (visible as a small lump under the skin), do not place the AED pad directly over it; shift the pad slightly to the side or lower. For <strong>Pregnant Victims</strong>, CPR should be performed normally, but if possible, the victim should be tilted slightly to their left side (if a second rescuer can help) to relieve pressure on the major blood vessels, though compressions remain the top priority.</p>
                        <p>Finally, consider <strong>Jewelry and Medication Patches</strong>. Piercings and necklaces should not be removed, but AED pads should not be placed directly over them to avoid electrical burns. Medication patches (like nitroglycerin or nicotine) should be removed with a gloved hand and the skin wiped clean before pad application. These adjustments ensure that the rescuer can adapt the gold-standard protocol to any environment without sacrificing safety or effectiveness.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Move victims to a dry surface and wipe the chest before AED use.</li><li>Avoid placing AED pads directly over pacemakers or medication patches.</li></ul></div>"""
                },
                {
                    'order': 12,
                    'title': 'The Rescuer\'s Journey: Psychological Care',
                    'content': """
                        <p>The act of performing CPR is one of the most stressful experiences a human can face. Rescuers often focus entirely on the victim, but the 2026 standard emphasizes the <strong>Psychological Well-being of the Rescuer</strong>. It is common to experience a "Critical Incident Stress" response after an event, which can include tremors, nausea, or difficulty sleeping. Understanding that these are normal physiological reactions to an abnormal situation is the first step toward recovery.</p>
                        <p>Many rescuers suffer from <strong>"Rescuer Guilt,"</strong> especially if the victim does not survive. It is vital to understand that cardiac arrest is an end-of-life event; your intervention is an attempt to reverse an otherwise terminal outcome. Even with perfect CPR and a rapid AED shock, survival is not guaranteed. The rescuer should focus on the fact that they provided the victim with their absolute best chance at life, which is a courageous and noble act regardless of the final medical result.</p>
                        <p>In the weeks following an event, if you experience persistent flashbacks, withdrawal from social activities, or severe anxiety, you should seek professional support. Many organizations now offer <strong>Psychological First Aid (PFA)</strong> for lay rescuers. Talking about the event with a mental health professional or a support group can prevent the development of PTSD. By taking care of your own mental health, you ensure that you remain ready and willing to help the next time a life-saving opportunity arises.</p>
                        <div class="alert alert-info"><strong>Key Takeaways:</strong><ul><li>Rescuers often experience high stress and guilt; these are normal reactions.</li><li>Focus on the act of helping rather than the final outcome.</li></ul></div>"""
                }
            ]

            for l_data in lessons:
                Lesson.objects.create(course=course, **l_data)
            
            self.stdout.write(self.style.SUCCESS(f'SUCCESS: CPR/AED updated with 12 World-Class Modules.'))
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'Error: {e}'))
