# Generated by Django 6.0.1 on 2026-02-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_price_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='related_lesson',
            field=models.ForeignKey(blank=True, help_text='The slide that teaches the answer to this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.lesson'),
        ),
    ]
