# Generated by Django 6.0.1 on 2026-02-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_related_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical & Healthcare'), ('workplace', 'Workplace Compliance'), ('safety', 'Safety & Trade')], default='medical', max_length=20),
        ),
    ]
