# Generated by Django 6.0.1 on 2026-02-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-priority', 'title']},
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = Shows higher on homepage (e.g. 100 for Top, 0 for standard)'),
        ),
    ]
